build:
  environment:
    php:
      version: 7.1

  tests:
    override:
      -
        command: 'composer build-code-coverage-clover'
        coverage:
          file: 'output/code-coverage/clover.xml'
          format: 'clover'
